# Docker Compose file for a Baikal server

version: "2"
services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - "8029:80"
    volumes:
      - mainDrive/apps/baikal/config:/var/www/baikal/config
      - mainDrive/apps/baikal/data:/var/www/baikal/Specific

volumes:
  config:
  data: