---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /mainDrive/apps/plex:/config
      - /mainDrive/media:/media
    restart: unless-stopped