---
version: "3.9"
services:
  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    volumes:
      - /mainDrive/apps/duplicati:/config #Config Files
      - /backupDrive1:/backupDrive1 #Backup Drive
      - /backupDrive2:/backupDrive2 #Backup Drive
      - /backupDrive3:/backupDrive3 #Backup Drive
      - /mainDrive:/mainDrive #What to Backup
      - /plexDrive:/plexDrive #What to Backup
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8200:8200
    network_mode: host
    restart: unless-stopped