---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - /mainDrive/apps/duplicati:/config #Config Files
      - /backupDrive1:/BackupStorage1 #Backup Storage
      - /backupDrive2:/BackupStorage2 #Backup Storage
      - /mainDrive:/mainDrive #What to Backup
      - /home:/home #What to Backup
    ports:
      - 8200:8200
    restart: unless-stopped