---
version: "2.1"
services:
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=501
      - PGID=20
      - TZ=Europe/Paris
    volumes:
      - /Config/Duplicati:/config #Config Files
      - /Backups:/BackupStorage #Backup Storage
      - /Config:/ConfigBackup #What to Backup
      - /Databases:/DatabaseBackup #What to Backup
    ports:
      - 8200:8200
    restart: unless-stopped