version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube-mp4
    restart: unless-stopped
    ports:
      - "8082:8081"
    volumes:
      - /mainDrive/media/youtube:/downloads
    deploy:
      resources:
        limits:
          cpus: '1'