version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    mem_limit: 2g
    memswap_limit: 3g
    cpus: 2.0
    pids_limit: 512
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /var/lib/docker-volumes/home-assistant:/config
    restart: always
  wyoming-piper:
    image: rhasspy/wyoming-piper
    container_name: wyoming-piper
    ports:
      - "10200:10200"
    volumes:
      - /var/lib/docker-volumes/piper:/data
    command: 
      - "--voice=en_US-lessac-medium"
      - "--speaker=0"
      - "--data-dir=/data"
    restart: always

volumes:
  config:
