version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /mainDrive/apps/home-assistant:/config
    restart: always
  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    ports:
      - "10300:10300"
    volumes:
      - /mainDrive/apps/whisper:/data
    command: [ "--model", "small-int8", "--language", "en" ]
    restart: unless-stopped
  wyoming-piper:
    image: rhasspy/wyoming-piper
    container_name: wyoming-piper
    ports:
      - "10200:10200"
    volumes:
      - /mainDrive/apps/piper:/data
    command: 
      - "--voice=en_US-lessac-medium"
      - "--language=en"
      - "--speaker=0"
      - "--quality=medium"
      - "--data-dir=/data"
    restart: unless-stopped

volumes:
  config: