version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /mainDrive/apps/home-assistant:/config
    restart: always
  wyoming-whisper:
    image: rhasspy/wyoming-whisper
    ports:
      - "10300:10300"
    volumes:
      - /mainDrive/apps/whisper:/data
    command: [ "--model", "base-int8", "--language", "en" ]
    restart: unless-stopped

volumes:
  config: