version: '3.8'
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - TZ=Europe/Paris
    ports:
      - 8123:8123
    volumes:
      - /mainDrive/apps/home-assistant:/config
    restart: always
  wyoming-piper:
    image: rhasspy/wyoming-piper
    container_name: wyoming-piper
    ports:
      - "10200:10200"
    volumes:
      - /mainDrive/apps/piper:/data
    command: 
      - "--voice=en_US-lessac-medium"
      - "--speaker=0"
      - "--data-dir=/data"
    restart: unless-stopped

volumes:
  config: