services:
  booklore:
    image: ghcr.io/adityachandelgit/booklore-app:latest
    container_name: booklore-backend
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "6060:6060"
    volumes:
      - /mainDrive/apps/bookLore/data:/app/data
      - /mainDrive/media/books:/books
    restart: unless-stopped

  mariadb:
    image: yobasystems/alpine-mariadb:latest
    container_name: booklore-mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /mainDrive/apps/bookLore/db:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s 
      timeout: 5s
      retries: 10