version: '2.1'
services:
    watchtower:
        image: nickfedor/watchtower:latest
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Europe/Paris
            - WATCHTOWER_MONITOR_ONLY=false
            - WATCHTOWER_SCHEDULE=0 0 4 ? * SAT
            - WATCHTOWER_CLEANUP=true
            - "WATCHTOWER_NOTIFICATION_URL=smtp://${MAILER_SENDER}:${MAILER_PASSWORD}@smtp.gmail.com:465/?fromaddress=${MAILER_SENDER}&toaddresses=${MAILER_SENDER}&encryption=ImplicitTLS&usestarttls=no&timeout=30s"
        restart: unless-stopped
