version: '2.1'
services:
    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - TZ=Europe/Paris
            - WATCHTOWER_MONITOR_ONLY=false
            - WATCHTOWER_SCHEDULE=0 0 4 ? * SAT
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${MAILER_SENDER}
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=${MAILER_SENDER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.gmail.com
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=465
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${MAILER_SENDER}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${MAILER_PASSWORD}
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_TIMEOUT=30
        restart: unless-stopped