version: '3.9'
services:
    kavita:
        image: lscr.io/linuxserver/kavita:latest
        volumes:
            - /mainDrive/media/books:/books
            - /mainDrive/apps/kativa:/kavita/config
        ports:
            - "5000:5000"
        environment:
              - TZ=Europe/Paris
              - PUID=1000
              - PGID=1000 
        restart: unless-stopped