version: '3.9'
services:
    kavita:
        image: jvmilazz0/kavita:latest
        volumes:
            - ./mainDrive/media/books:/books
            - ./mainDrive/apps/kativa:/kavita/config
        ports:
            - "5000:5000"
        environment:
              - TZ=Europe/Paris
              - PUID=0
              - PGID=0
        restart: unless-stopped