version: '3'
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    volumes:
      - /mainDrive:/srv/mainDrive
      - /plexDrive:/srv/plexDrive
      - /mainDrive/apps/file-browser/db:/database
      - /mainDrive/apps/file-browser/config:/config
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8095:80
    restart: unless-stopped