version: '3'

services:
  vikunja:
    image: vikunja/vikunja
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${VIKUNJA_SERVICE_PUBLICURL}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
    ports:
      - 3756:3456
    volumes:
      - /mainDrive/apps/vikunja/app:/app/vikunja/files
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - /mainDrive/apps/vikunja/db:/var/lib/mysql
    restart: unless-stopped