version: '3'

services:
  vikunja:
    image: vikunja/vikunja:latest
    environment:
      VIKUNJA_SERVICE_PUBLICURL: ${VIKUNJA_SERVICE_PUBLICURL}
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      VIKUNJA_DATABASE_TYPE: mysql
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_JWTSECRET: ${VIKUNJA_SERVICE_JWTSECRET}
      VIKUNJA_MAILER_ENABLED: true
      VIKUNJA_MAILER_HOST: smtp.gmail.com
      VIKUNJA_MAILER_PORT: 465
      VIKUNJA_MAILER_USERNAME: ${MAILER_SENDER}
      VIKUNJA_MAILER_PASSWORD: ${MAILER_PASSWORD}
      VIKUNJA_MAILER_FROMEMAIL: ${MAILER_SENDER}
      VIKUNJA_MAILER_FORCESSL: true
    ports:
      - 3756:3456
    volumes:
      - /var/lib/docker-volumes/vikunja/app:/app/vikunja/files
    depends_on:
      - db
    restart: always
  db:
    image: yobasystems/alpine-mariadb:latest
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: vikunja
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: vikunja
    volumes:
      - /var/lib/docker-volumes/vikunja/db:/var/lib/mysql
    restart: always