version: '3'
services:
  glances-web:
    image: nicolargo/glances:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mainDrive:/mnt/mainDrive
      - /plexDrive:/mnt/plexDrive
      - /backupDrive1:/mnt/backupDrive1
      - /backupDrive2:/mnt/backupDrive2
      - /backupDrive3:/mnt/backupDrive3
    ports:
      - "61208:61208"
    command: glances -w