version: '3'
services:
  monitoring:
    image: nicolargo/glances
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mainDrive:/mnt/mainDrive
      - /plexDrive:/mnt/plexDrive
      - /backupDrive1:/mnt/backupDrive1
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"