version: '3'

services:
  monitoring:
    image: nicolargo/glances
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/mainDrive:/mnt/mainDrive
      - ~/backupDrive1:/mnt/backupDrive1
      - ~/backupDrive2:/mnt/backupDrive2
    environment:
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"