version: '3'

services:
  whoami:
    image: traefik/whoami

  monitoring:
    image: nicolargo/glances
    restart: always
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=-w"