---
version: "3.8"
services:
  librum:
    image: librum
    hostname: librum
    container_name: librum
    ports:
      - 5133:5133
    networks:
      - librum
    volumes:
      - /srv/dev-disk-by-uuid-e5aad6d5-19c3-4432-b7e6-ce7d7ed33a09/apps/librum/server:/var/lib/librum-server/librum_storage
    environment:
      - JWTValidIssuer=librumapp
      - JWTKey=${JWTKey}
      - SMTPEndpoint=smtp.sendgrid.net
      - SMTPUsername=apikey
      - SMTPPassword=${SMTPPassword}
      - SMTPMailFrom=william.guinaudie@gmail.com
      - DBConnectionString=Server=mariadb;port=3306;Database=librum;Uid=librum;Pwd=mariadb;
      - AdminEmail=william.guinaudie@gmail.com
      - AdminPassword=${AdminPassword}
    restart: unless-stopped
    depends_on:
      - librum_db

  librum_db:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    hostname: mariadb
    container_name: librum_db
    networks:
      - librum
    volumes:
      - /srv/dev-disk-by-uuid-e5aad6d5-19c3-4432-b7e6-ce7d7ed33a09/apps/librum/db:/var/lib/mysql
    environment:
      - MARIADB_USER=librum
      - MARIADB_PASSWORD=mariadb
      - MARIADB_DATABASE=librum
      - MARIADB_ROOT_PASSWORD=mariadb
    restart: unless-stopped

networks:
  librum:
    name: "librum"

volumes:
  librum:
    name: "librum"
  librum_db:
    name: "librum_db"