---
version: "3.8"
services:
  librum:
    image: ghcr.io/librum-reader/librum-server:latest
    hostname: librum
    container_name: librum
    ports:
      - 5000:5000
    networks:
      - librum
    volumes:
      - /srv/dev-disk-by-uuid-e5aad6d5-19c3-4432-b7e6-ce7d7ed33a09/apps/librum/storage:/var/lib/librum-server/librum_storage
    environment:
      - JWTValidIssuer=librumapp
      - JWTKey=${JWTKey}
      - SMTPEndpoint=smtp.sendgrid.net
      - SMTPUsername=apikey
      - SMTPPassword=${SMTPPassword}
      - SMTPMailFrom=william.guinaudie@gmail.com
      - DBConnectionString=Server=mariadb;port=3306;Database=librum;Uid=librum;Pwd=mariadb;
      - AdminEmail=william.guinaudie@gmail.com
      - AdminPassword=${AdminPassword}
      - OpenAIToken=${OpenAIToken}
    restart: unless-stopped
    depends_on:
      - librum_db:
          condition: service_healthy            # Ensures the DB is up before the server.
  
  librum_db:
    image: yobasystems/alpine-mariadb:latest
    hostname: mariadb
    container_name: librum_db
    networks:
      - librum
    volumes:
      - /srv/dev-disk-by-uuid-e5aad6d5-19c3-4432-b7e6-ce7d7ed33a09/apps/librum/db:/var/lib/mysql
    environment:
      - MARIADB_USER=librum
      - MARIADB_PASSWORD=mariadb
      - MARIADB_DATABASE=librum
      - MARIADB_ROOT_PASSWORD=mariadb
    restart: unless-stopped
    healthcheck:                              # Ensures the DB is up before the server.
      test: ["CMD", "mariadb-admin", "ping", "-u", "librum", "-p'mariadb'", "-h", "localhost"]
      interval: 20s
      timeout: 40s
      retries: 3
      start_period: 30s

networks:
  librum:
    name: "librum"

volumes:
  librum:
    name: "librum"
  librum_db:
    name: "librum_db"
