services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /mainDrive/apps/beszel:/beszel_data
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mainDrive/apps/beszel-agent:/var/lib/beszel-agent
    environment:
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: ${BESZEL_HUB_URL}