version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube:2026.08.28
    container_name: metube
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /mainDrive/media:/downloads
