version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - /mainDrive/media:/downloads
    deploy:
      resources:
        limits:
          cpus: '1'