version: '3.3'
services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - /mainDrive/torrents:/data
      - /mainDrive/media:/media
      - /Config
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=france
      - OPENVPN_USERNAME=p3685704
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn
    restart: unless-stopped
