version: "3.9"

services:
  doku:
    image: amerkurev/doku
    container_name: doku
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro