
version: '3.8'
services:
  ffmpeg:
    image: jrottenberg/ffmpeg:4.1-alpine38-arm32v6
    volumes:
      - /mainDrive/media/youtube:/downloads
    command: >
      bash -c "while true; do
        for file in /downloads/*.mp4; do
          [ -e "$$file" ] || continue
          output_file=$$(dirname "$$file")/$$(basename "$$file" .mp4)_converted.mp4
          ffmpeg -i "$$file" -c:v libx264 -c:a aac "$$output_file" && rm "$$file" && mv "$$output_file" "$$file"
        done
        sleep 10
      done"
    deploy:
      resources:
        limits:
          cpus: '1'